trigger:
- master
- releases/*
- node6hotfixes/*

resources:
  repositories:
  - repository: AzureDevOps
    type: git
    endpoint: AzureDevOps
    name: AzureDevOps/AzureDevOps

jobs:

# All tasks on Windows
- job: build_all_windows
  displayName: Build all tasks (Windows)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 120
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Windows_NT

# Publish on Windows
- job: publish_windows
  displayName: Publish
  dependsOn:
  - build_all_windows
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'), eq(variables.os, 'Windows_NT'))
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/publish-steps.yml

# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
  pool:
    vmImage: ubuntu-18.04
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Linux





